services:
  backend:
    build: ./
    entrypoint: dotnet ElectronicDocumentManagement.dll
    restart: always
    environment:
      - ASPNETCORE_URLS=https://backend:5290
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert
      - PORT=5290
    command: dotnet ElectronicDocumentManagement.dll
    depends_on:
      - postgreSQL
    networks:
      - aspnetcore-network
    deploy:
      replicas: 1
  
  postgreSQL:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=docsdb
    ports:
      - "5433:5432"
    restart: always
    networks:
      - aspnetcore-network
  
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
    ports:
      - "443:443"
    networks:
      - aspnetcore-network
    depends_on:
      - backend

networks:
  aspnetcore-network:
    driver: bridge


